#!/bin/bash

echo "Building the PortableApps.com Launcher Manual..."
	cd Manual
	make release
	cd ..

echo "Building the PortableApps.com Launcher Generator..."
	makensisu GeneratorWizard.nsi

echo "Building the PortableApps.com Launcher..."
	cd ../..
	chmod +x PortableApps.comLauncherGenerator.exe
	PortableApps.comLauncherGenerator.exe "`winepath -w $PWD`"

echo "Building the PortableApps.com Launcher installer..."
	paiu $PWD

echo "Uploading the installer..."
	export make_release_py="$PWD/Other/Source/make_release.py"
	cd ..
	echo -n 'Please enter your SourceForge username: (default: chriswombat) '
	read sfusername
	if [ "$sfusername" = "" ]; then
		export sfusername=chriswombat
	fi
	$make_release_py | sftp $sfusername,portableapps@frs.sourceforge.net

echo "Done!"
